export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';

export const LOAD_REQUESTS_SUCCESS = 'LOAD_REQUESTS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_STATIC_LISTS = 'LOAD_STATIC_LISTS';
